### ISSUE TITLE
Home Screen error - if in stage cracking - 

### ISSUE THREAD

**Issue by bbr111** [AdrianVollmer/Crack-O-Matic#1]
[2021-05-07 15:03:30,342] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/crackomatic/.local/lib/python3.7/site-packages/crackomatic/flask.py", line 144, in home
    status = backend.get_status()
  File "/home/crackomatic/.local/lib/python3.7/site-packages/crackomatic/backend.py", line 370, in get_st                                                   atus
    eta = status['ETA'] - dt.now()
TypeError: unsupported operand type(s) for -: 'str' and 'datetime.datetime'

**Comment by AdrianVollmer** [comment]
Fixed in 55ee0d3c124507bd9ba7d7ca9428230274a0cc08 and 52c22c6.

Thanks for the report!

**Comment by bbr111** [comment]
Thanks.

I will test again.
